### ISSUE TITLE
Variable content in Navbar depending on the user being logged in

### ISSUE THREAD

**Issue by VanRhapsody** [TheDarkun/Elevators#10]
**Proposal**
The Navbar component should have an if statement which checks whether she session variable for being logged in is True and based on that will display either the user's profile picture and username (could possibly be a component too) or an option to sign in

**Detail**
The if statement depends on how we're going to check whether the user is logged in. This approach is mainly used in PHP

**Comment by TheDarkun** [comment]
Also, this does not contain any **logout** functionality and should be covered in another issue regarding both **backend** and **frontend**.
